In [1]:
#Here is some code to represent a simple 2-player normal form game.
#This code can be used to set up the matrix, compute utilities of the players and generate Nash equilibria.

import nashpy as nash

In [2]:
nash.__version__

'0.0.19'

In [3]:
import numpy as np

In [4]:
#Below represents the set up for chicken game.
A = np.array([[6, 2], [8, 0]])
B = np.array([[6, 8], [2, 0]])
chicken_game=nash.Game(A,B)
chicken_game




Bi matrix game with payoff matrices:

Row player:
[[6 2]
 [8 0]]

Column player:
[[6 8]
 [2 0]]

In [5]:
#utility if both players play their first strategy (aggressive)
sigma_r = np.array([1, 0])
sigma_c = np.array([1, 0])
chicken_game[sigma_r,sigma_c]

array([6, 6])

In [6]:
#utility if both players randomise over both strategies uniformly (0.5A,0.5P)
sigma_r=np.array([0.5,0.5])
sigma_c=np.array([0.5,0.5])
chicken_game[sigma_r,sigma_c]

array([4., 4.])

In [7]:
#use support enumeration algorithm in nashpy to generate equilibria of the game (2 PSNE, 1 MSNE)
equilibria=chicken_game.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([0., 1.]))
(array([0., 1.]), array([1., 0.]))
(array([0.5, 0.5]), array([0.5, 0.5]))
